= Robot Names

== c3po
C-3PO is a droid programmed for etiquette and protocol, built by the heroic Jedi Anakin Skywalker, and a constant companion to astromech R2-D2. Over the years, he was involved in some of the galaxy's most defining moments and thrilling battles -- and is fluent in more than seven million forms of communication.

== gort
Gort is a fictional humanoid robot that appeared first in the 1951 20th Century Fox American science fiction film The Day the Earth Stood Still and later in its 2008 remake.

== marc13
The M.A.R.K 13 is the main antagonist of the 1990 British science fiction horror film Hardware. It is a homicidal robot built by the government to commit genocide.

== marvin
Marvin the Paranoid Android is a fictional character in The Hitchhiker's Guide to the Galaxy series by Douglas Adams. Marvin is the ship's robot aboard the starship Heart of Gold.

== r2d2
R2-D2 was an R2-series astromech droid manufactured by Industrial Automaton with masculine programming. A smart, spunky droid who would serve a multitude of masters over his lifetime, R2-D2 was never given a full memory wipe nor did he ever receive new programming, with these factors resulting in an adventurous and independent attitude. Often finding himself in pivotal moments in galactic history, his bravery and ingenuity saved the galaxy on numerous occasions.

== t1000
In the Terminator franchise, the T-1000 is a Terminator, a line of android assassins created by the artificial intelligence Skynet. In the future, Skynet is engaged in a war against humans, who are led by John Connor. In Terminator 2, the T-1000 is sent back in time to kill young John. The T-1000 is made up of a liquid metal, known in the film as mimetic polyalloy, which allows it to shapeshift into other people or objects that come into contact with it.